// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVPdJQzb_-tEr37dijO966jfyIe2ko0v8',
    appId: '1:1094040548294:web:74ecc2fb5cd68ae49238c7',
    messagingSenderId: '1094040548294',
    projectId: 'the-visual-book',
    authDomain: 'the-visual-book.firebaseapp.com',
    storageBucket: 'the-visual-book.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3HIqGN9oKRdLh_wHenA_Dy7Ai20Mvkh0',
    appId: '1:1094040548294:android:c27e37f9f5b19d399238c7',
    messagingSenderId: '1094040548294',
    projectId: 'the-visual-book',
    storageBucket: 'the-visual-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7tOT-PtvNYs2PHtLX48xauGupKv85_HU',
    appId: '1:1094040548294:ios:932e4a27043933879238c7',
    messagingSenderId: '1094040548294',
    projectId: 'the-visual-book',
    storageBucket: 'the-visual-book.appspot.com',
    iosClientId: '1094040548294-3t8bm5mkttdfcdj79e2sdrpgccad60o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.theVisiualBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7tOT-PtvNYs2PHtLX48xauGupKv85_HU',
    appId: '1:1094040548294:ios:12d6205db774d3a59238c7',
    messagingSenderId: '1094040548294',
    projectId: 'the-visual-book',
    storageBucket: 'the-visual-book.appspot.com',
    iosClientId: '1094040548294-umk3dt56v7oah3tdcfo4f1tu3c2tbf3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.theVisiualBook.RunnerTests',
  );
}
